-- Container monitor policy.
--
-- Physical connectors are kept disabled by omarchy-monitor-guard, which also
-- handles connectors that reappear after an Omarchy display refresh. Do not
-- install a monitor rule here: this file is loaded again on every Hyprland
-- reload, and a fixed scale/resolution rule would overwrite changes made in
-- Omarchy's display utility. Startup resolution and scale are applied once by
-- omarchy-headless-init; subsequent display settings remain user-controlled.
